Busticketsales/Areas/Admin/Controllers/MenuFooterController.cs
using Busticketsales.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Busticketsales.Models;

namespace RESTORANS.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class MenufooterController : Controller
    {
        private readonly Datacontext _context;
        public MenufooterController(Datacontext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var mnList = _context.Menus.Where(m => m.Position == 2).OrderBy(m => m.MenuID).ToList();
            return View(mnList);
        }

        //thêm mới menu
        public IActionResult Create()
        {
            var mnList = (from m in _context.Menus.Where(m => m.Position == 2)
                          select new SelectListItem()
                          {
                              Text = m.MenuName,
                              Value = m.MenuID.ToString(),
                          }).ToList();
            mnList.Insert(0, new SelectListItem()
            {
                Text = "---- select-----",
                Value = "0"
            });
            ViewBag.mnList = mnList;
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Menu mn)
        {
            if (ModelState.IsValid)
            {
                _context.Menus.Add(mn);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(mn);
        }
        // Chính sửa menu
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var mn = _context.Menus.Find(id);
            if (mn == null)
            {
                return NotFound();
            }
            var mnList = (from m in _context.Menus.Where(m => m.Position == 2)
                          select new SelectListItem()
                          {
                              Text = m.MenuName,
                              Value = m.MenuID.ToString()
                          }).ToList();
            mnList.Insert(0, new SelectListItem()
            {
                Text = "--- select -----",
                Value = "0"
            });
            ViewBag.mnList = mnList;
            return View(mn);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Menu mn)
        {
            if (ModelState.IsValid)
            {
                _context.Menus.Update(mn);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(mn);
        }

        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var menu = _context.Menus
                        .FirstOrDefault(m => (m.MenuID == id) && (m.IsActive == true));
            if (menu == null)
            {
                return NotFound();
            }
            return View(menu);
        }
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var mn = _context.Menus.Find(id);
            if (mn == null)
            {
                return NotFound();
            }
            return View(mn);
        }
        [HttpPost]
        public IActionResult Delete(int id)
        {
            var deleMenu = _context.Menus.Find(id);
            if (deleMenu == null)
            {
                return NotFound();
            }
            _context.Menus.Remove(deleMenu);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Busticketsales/Areas/Admin/Views/Menufooter/Create.cshtml
@model Busticketsales.Models.Menu
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div id="main" class="main">
    <div class="container shadow p-5">
        <div class="row pb-2">
            <h2>Thêm mới menu</h2>
        </div>
        <form method="post">
            <div asp-validation-summary="All"></div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label asp-for="MenuName">MenuName</label>
                    <input type="text" class="form-control mb-3" asp-for="MenuName" placeceholder="Nhập tên menu" />
                    <span asp-validation-for="MenuName" class="alert-danger"></span>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label asp-for="Levels">Levels</label>
                    <select asp-for="Levels" class="form-select" id="Levels">
                        <option value="1">1</option>
                        <option value="2">2</option>
                    </select>
                </div>
            </div>
            <div class="form-group col-md-6">
                <div class="alert-danger" asp-validation-summary="ModelOnly"></div>
                <label asp-for="ParentID">ParentID</label>
                <select asp-for="ParentID" class="form-control" asp-items="@(new SelectList(ViewBag.mnList, "Value","Text"))">  </select>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="Link">Link</label>
                <input type="text" class="form-control mb-3" asp-for="Link" placeholder="Enter Link" />
                <span asp-validation-for="Link" class="alert-danger"></span>
            </div>
            <div class="form-group col-md-6 d-none">
                <label asp-for="MenuOrder">MenuOrder</label>
                <input type="text" class="form-control mb-3" asp-for="MenuOrder" value="1" placeholder="Enter MenuOrder" />
                <span asp-validation-for="MenuOrder" class="alert-danger"></span>
            </div>
            <div class="form-group col-md-6 d-none">
                <label asp-for="Position">Position</label>
                <input type="text" class="form-control mb-3" asp-for="Position" value="2" placeholder="Enter Position" />
                <span asp-validation-for="Position" class="alert-danger"></span>
            </div>
            <div class="form-group mb-5 mt-5">
                <label>
                    @Html.CheckBox("IsActive",false)
                    Hiển thị
                </label>
            </div>
            <button type="Submit" class="btn btn-lg btn-primary p-2"><i class="bi bi-file-plus-fill"></i>Lưu</button>
            <a asp-controller="Menufooter" asp-action="Index" class="btn btn-lg btn-warning p-2">Quay lại</a>
        </form>
    </div>
</div>

Busticketsales/Areas/Admin/Views/Menufooter/Delete.cshtml
@model Busticketsales.Models.Menu
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<main id="main" class="main">
    <div class="pagetitle">
        <h2>Xác nhận xóa menu</h2>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label asp-for="MenuID">MenuID</label>
            <input type="text" class="form-control mb-3" asp-for="MenuID" disabled />
        </div>

        <div class="form-group col-md-6">
            <label asp-for="MenuName">MenuName</label>
            <input type="text" class="form-control mb-3" asp-for="MenuName" disabled />
        </div>
    </div>

    <form asp-action="Delete" method="post">
        <input type="hidden" asp-for="MenuID" />
        <a class="btn btn-lg btn-warning p-2 mr-5" href="javascript:history.back()">
            <i class="bi bi-arrow-left-circle"></i> Quay lại
        </a>
        <button type="submit" class="btn btn-lg btn-danger p-2">
            <i class="bi bi-trash-fill"></i> Xóa menu
        </button>
    </form>

</main>

Busticketsales/Areas/Admin/Views/Menufooter/Details.cshtml
@model Busticketsales.Models.Menu
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<main id="main" class="main">
    <div class="pagetitle">
        <h2>Xem Menu</h2>
    </div>
    <div class="container-fluid py-5 wow fadeInUp" data-wow-delay="0.1s">
        <div class="container py-5">
            <div class="row g-5">
                <div class="col-lg-8">
                    <!-- Blog Detail Start -->
                    <div class="mb-5">
                        <label>Tên Menu : </label>
                        <h5 class="mb-4">@Html.DisplayFor(model => model.MenuName)</h5>
                        <label>Mức : </label>
                        <p>@Html.Raw(Model.Levels) </p>
                        <label>Cấp độ : </label>
                        <p>@Html.Raw(Model.ParentID) </p>
                        <label>Ẩn hiện : </label>
                        <p>@Html.Raw(Model.IsActive) </p>
                        <label>Link Menu : </label>
                        <p>@Html.Raw(Model.Link) </p>

                    </div>
                    <a asp-controller="Menufooter" asp-action="Index" class="btn btn-lg btn-warning p-2">Quay lại</a>

                </div>
            </div>
        </div>
    </div>
</main>

Busticketsales/Areas/Admin/Views/Menufooter/Edit.cshtml
@model Busticketsales.Models.Menu
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<main id="main" class="main">

    <div class="container shadow p-5">
        <div class="pagetitle">
            <h2>Sửa menu</h2>
        </div>
        <form method="post" asp-action="Edit">
            <div asp-validation-summary="All"></div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <input type="text" class="form-control mb-3" asp-for="MenuID" hidden />
                </div>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="MenuName">MenuName</label>
                <input type="text" class="form-control mb-3" asp-for="MenuName" placeholder="Nhập tên menu" />
                <span asp-validation-for="MenuName" class="alert-danger"></span>
            </div>

            <div class="form-row">
                <div class="form-group col-md-6">
                    <label asp-for="Levels">Levels</label>
                    <select asp-for="Levels" class="form-select" id="Levels">
                        <option value="1">1</option>
                        <option value="2">2</option>
                    </select>
                </div>
            </div>

            <div class="form-group col-md-6">
                <div class="alert-danger" asp-validation-summary="ModelOnly"></div>
                <label asp-for="ParentID">ParentID</label>
                <select asp-for="ParentID" class="form-control" asp-items="@(new SelectList(ViewBag.mnList, "Value","Text"))">
                </select>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="Link">Link</label>
                <input type="text" class="form-control mb-3" asp-for="Link" placeplaceholder="Enter Link" />
                <span asp-validation-for="Link" class="Alert-danger"></span>
            </div>
            <div class="form-group col-md-6 d-none">
                <label asp-for="Position">Position</label>
                <input type="text" class="form-control mb-3" asp-for="Position" value="2" placeplaceholder="Enter Position" />
                <span asp-validation-for="Position" class="Alert-danger"></span>
            </div>
            <div class="form-group mt-3 mb-5">
                <label>
                    @Html.CheckBox("IsActive",Model.IsActive)
                    Hiển thị
                </label>
            </div>
            <button type="submit" class="btn btn-lg btn-primary p-2"><i class="bi bi-file-plus-fill"></i>Lưu</button>
            <a asp-controller="Menufooter" asp-action="Index" class="btn btn-lg btn-warning p-2">Quay lại</a>

        </form>
    </div>
</main>

Busticketsales/Areas/Admin/Views/Menufooter/Index.cshtml
@using Busticketsales.Models;
@model IList<Menu>
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<main id="main" class="main">
    <div class="pagetitle">
        <h2> Danh sách Menufooter</h2>
    </div>

    <p>
        <a type="button" class="btn btn-success" asp-area="Admin" asp-controller="Menufooter" asp-action="Create">
            <i class="bi bi-file-earmark-text me-1"></i> Thêm menu
        </a>
    </p>
    <section class="section dashboard">
        <div class="row">
            <div class="col-12">
                <div class="card recent-sales overflow-auto">
                    <div class="card-body mt-4">
                        <table class="table table-borderless datatable">
                            <thead>
                                <tr>
                                    <th class="col-1 text-center">#</th>
                                    <th class="col-3 text-center">Tiêu đề</th>
                                    <td class="col-2 text-center">Mức</td>
                                    <td class="col-2 text-center">Menu cha</td>
                                    <td class="col-1 text-center">Thứ tự</td>
                                    <td class="col-1 text-center">Ẩn/hiện</td>
                                    <th class="col-2 text-center">Chức năng</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <th class="text-center" scope="row"> @item.MenuID</th>
                                        <td>
                                            <a asp-area="Admin" asp-controller="Menu" asp-action="Details"
                                           asp-route-id="@item.MenuID" class="text-primary">@item.MenuName</a>
                                        </td>
                                        <td class="text-center">@item.Levels</td>
                                        <td class="text-center">@item.ParentID</td>
                                        <td class="text-center">@item.MenuOrder</td>
                                        <td class="text-center">@item.IsActive</td>
                                        <td class="text-center">
                                            <a asp-area="Admin" asp-controller="MenuFooter" asp-action="Details"
                                           asp-route-id="@item.MenuID" class="btn bg-success btn-sm"
                                               title="Xem nội dung menu"><i class="text-white bi bi-eye"></i></a>

                                            <a asp-area="Admin" asp-controller="MenuFooter" asp-action="Edit"
                                           asp-route-id="@item.MenuID" class="btn bg-warning btn-sm"
                                               title="Sửa nội dung menu"><i class="text-white bi bi-pencil"></i></a>

                                            <a asp-area="Admin" asp-controller="MenuFooter" asp-action="Delete"
                                           asp-route-id="@item.MenuID" class="btn btn-danger btn-sm"
                                               title="Xóa nội dung menu"><i class="bi bi-trash"></i></a>
                                        </td>
                                    </tr>
                                }


                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>